# Server
server.port=8080
spring.application.name=4mulaQuery API

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
# Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=4mulamind@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
gemini.api.key=${GEMINI_API_KEY}