# Server
server.port=8080
spring.application.name=4mulaQuery API

# MongoDB
spring.data.mongodb.uri=mongodb+srv://4mulamind_db_user:vo7cbh6tlwPcfijS@4mulaquery.olxlt4z.mongodb.net/4mulaquery?appName=4mulaQuery

# Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=4mulamind@gmail.com
spring.mail.password=bfaozvvtgalvsmwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true