package com.formulaquery.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Service responsible for translating natural-language queries into
 * structured filter conditions for a flexible, dynamically generated dataset.
 *
 * <p>The dataset schema is determined dynamically, typically from columns
 * created after importing a CSV file. Unlike a fixed-schema query service,
 * this service can work with different datasets containing different columns.</p>
 *
 * <p>The service uses the Google Gemini API to convert a user's natural-language
 * request into a structured JSON filter specification. The generated result is
 * then validated against the actual dataset schema before being applied to
 * the records.</p>
 *
 * <p>Supported filtering operations include:</p>
 * <ul>
 *     <li>Equal to: {@code =}</li>
 *     <li>Not equal to: {@code !=}</li>
 *     <li>Greater than: {@code >}</li>
 *     <li>Less than: {@code <}</li>
 *     <li>Greater than or equal to: {@code >=}</li>
 *     <li>Less than or equal to: {@code <=}</li>
 *     <li>Partial text match: {@code contains}</li>
 * </ul>
 *
 * <p>Multiple conditions can be combined using {@code AND} or {@code OR} logic.</p>
 */
@Service
public class FlexibleNLPQueryService {

    /**
     * Google Gemini API key injected from the application configuration.
     *
     * <p>Expected property:</p>
     * <pre>{@code
     * gemini.api.key=YOUR_API_KEY
     * }</pre>
     */
    @Value("${gemini.api.key}")
    private String apiKey;

    /**
     * Gemini model used for natural-language-to-filter translation.
     */
    private static final String MODEL = "gemini-3.5-flash-lite";

    /**
     * Template used to construct the Gemini generateContent API URL.
     *
     * <p>The first placeholder represents the model name and the second
     * placeholder represents the API key.</p>
     */
    private static final String GEMINI_API_URL_TEMPLATE =
            "https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s";

    /**
     * HTTP client used to communicate with the Gemini API.
     *
     * <p>A connection timeout of 10 seconds is configured to avoid waiting
     * indefinitely when the external API is unavailable.</p>
     */
    private final HttpClient httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .build();

    /**
     * Jackson ObjectMapper used for:
     * <ul>
     *     <li>Converting Java objects into JSON request bodies.</li>
     *     <li>Parsing JSON responses returned by Gemini.</li>
     * </ul>
     */
    private final ObjectMapper mapper = new ObjectMapper();

    /**
     * Represents one filter condition.
     *
     * <p>Example:</p>
     * <pre>{@code
     * {
     *   "field": "age",
     *   "op": ">",
     *   "value": "30"
     * }
     * }</pre>
     */
    public static class Condition {

        /**
         * Dataset column on which the condition should be applied.
         */
        public String field;

        /**
         * Comparison operator.
         *
         * <p>Examples: {@code =}, {@code !=}, {@code >}, {@code contains}</p>
         */
        public String op;

        /**
         * Value against which the actual record value is compared.
         */
        public String value;
    }

    /**
     * Represents the structured result generated from a natural-language query.
     *
     * <p>The command can be one of:</p>
     * <ul>
     *     <li>{@code FILTER} - Filter records using one or more conditions.</li>
     *     <li>{@code ALL} - Return every record without filtering.</li>
     *     <li>{@code UNSUPPORTED} - The requested operation is not supported.</li>
     * </ul>
     */
    public static class FlexibleNLPResult {

        /**
         * Command generated by the NLP model.
         *
         * <p>Allowed values: {@code FILTER}, {@code ALL}, {@code UNSUPPORTED}</p>
         */
        public String command;

        /**
         * Logical operator used when multiple conditions exist.
         *
         * <p>Allowed values: {@code AND} or {@code OR}</p>
         */
        public String logic;

        /**
         * List of filter conditions generated from the user query.
         */
        public List<Condition> conditions = new ArrayList<>();

        /**
         * Explanation of why a request is unsupported.
         *
         * <p>This value is normally populated only when the command is
         * {@code UNSUPPORTED}.</p>
         */
        public String reason;
    }

    /**
     * Set of operators that are allowed to be used in filter conditions.
     *
     * <p>Validation prevents the AI model from returning unsupported operators.</p>
     */
    private static final Set<String> ALLOWED_OPS =
            Set.of("=", "!=", ">", "<", ">=", "<=", "contains");

    /**
     * Translates a natural-language query into a validated filter specification.
     *
     * <p>The method performs the following steps:</p>
     * <ol>
     *     <li>Builds a system prompt using the actual dataset schema.</li>
     *     <li>Sends the user query to the Gemini API.</li>
     *     <li>Requests a JSON-only response.</li>
     *     <li>Parses the Gemini response into a {@link FlexibleNLPResult}.</li>
     *     <li>Removes Markdown code fences if Gemini returns them.</li>
     *     <li>Validates fields, commands, and operators.</li>
     * </ol>
     *
     * @param datasetSchema the actual column names available in the dataset
     * @param userQuery the natural-language query entered by the user
     * @return a validated structured NLP result
     * @throws Exception if the Gemini API request or JSON parsing fails
     */
    public FlexibleNLPResult translate(
            List<String> datasetSchema,
            String userQuery
    ) throws Exception {

        // Build instructions that tell Gemini exactly which dataset columns exist.
        String systemPrompt = buildSystemPrompt(datasetSchema);

        /*
         * Create the JSON request body expected by the Gemini generateContent API.
         *
         * systemInstruction contains rules for translating the query.
         * contents contains the actual query submitted by the user.
         * generationConfig requests JSON output instead of normal text.
         */
        String requestBody = mapper.writeValueAsString(new Object() {

            /**
             * System-level instructions given to the AI model.
             */
            public final Object systemInstruction = new Object() {
                public final Object[] parts = {new Object() {
                    public final String text = systemPrompt;
                }};
            };

            /**
             * User-provided natural-language query.
             */
            public final Object[] contents = {new Object() {
                public final Object[] parts = {new Object() {
                    public final String text = userQuery;
                }};
            }};

            /**
             * Instruct Gemini to return the response as JSON.
             */
            public final Object generationConfig = new Object() {
                public final String responseMimeType = "application/json";
            };
        });

        // Insert the selected model name and API key into the API URL.
        String url = String.format(GEMINI_API_URL_TEMPLATE, MODEL, apiKey);

        /*
         * Build the HTTP POST request.
         *
         * The request body contains the system instructions and the user's query.
         */
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                .build();

        // Send the request synchronously and receive the response as a String.
        HttpResponse<String> response =
                httpClient.send(
                        request,
                        HttpResponse.BodyHandlers.ofString()
                );

        /*
         * Stop processing if Gemini returns an unsuccessful HTTP status.
         * The response body is included to help diagnose API errors.
         */
        if (response.statusCode() != 200) {
            throw new RuntimeException(
                    "Gemini API error: "
                            + response.statusCode()
                            + " "
                            + response.body()
            );
        }

        // Parse the complete JSON response returned by Gemini.
        JsonNode root = mapper.readTree(response.body());

        // Extract the candidates array containing the generated response.
        JsonNode candidates = root.path("candidates");

        // Ensure that Gemini actually returned at least one candidate.
        if (!candidates.isArray() || candidates.isEmpty()) {
            throw new RuntimeException(
                    "Gemini returned no candidates. Full response: "
                            + response.body()
            );
        }

        /*
         * Extract the generated text from the first candidate.
         *
         * Expected Gemini response structure:
         * candidates[0].content.parts[0].text
         */
        String rawText = candidates.get(0)
                .path("content")
                .path("parts")
                .get(0)
                .path("text")
                .asText();

        // Remove Markdown code fences if the model included them.
        String cleanJson = stripCodeFences(rawText);

        // Parse the cleaned JSON generated by the model.
        JsonNode parsed = mapper.readTree(cleanJson);

        // Create the structured result object.
        FlexibleNLPResult result = new FlexibleNLPResult();

        // Read the generated command.
        result.command = parsed.path("command").asText();

        /*
         * Use AND as the default logic if Gemini does not explicitly
         * provide a logic field.
         */
        result.logic = parsed.hasNonNull("logic")
                ? parsed.get("logic").asText()
                : "AND";

        // Read the unsupported reason when it is available.
        result.reason = parsed.hasNonNull("reason")
                ? parsed.get("reason").asText()
                : null;

        /*
         * Convert every JSON condition returned by Gemini into a
         * Condition Java object.
         */
        if (parsed.has("conditions") && parsed.get("conditions").isArray()) {

            for (JsonNode c : parsed.get("conditions")) {

                Condition cond = new Condition();

                // Extract the dataset column name.
                cond.field = c.path("field").asText();

                // Extract the comparison operator.
                cond.op = c.path("op").asText();

                // Extract the expected comparison value.
                cond.value = c.path("value").asText();

                // Add the condition to the final result.
                result.conditions.add(cond);
            }
        }

        /*
         * Validate the AI-generated result before it is used.
         *
         * This ensures that:
         * - The command is known.
         * - FILTER has at least one condition.
         * - Every field exists in the actual dataset.
         * - Every operator is supported.
         */
        validate(result, datasetSchema);

        // Return the validated structured filter result.
        return result;
    }

    /**
     * Applies a translated filter specification to the actual dataset records.
     *
     * <p>Each record is evaluated against every generated condition.
     * Multiple conditions are combined using either AND or OR logic.</p>
     *
     * <p>For each comparison, the service first attempts numeric comparison.
     * If either value cannot be parsed as a number, it falls back to
     * case-insensitive string comparison.</p>
     *
     * @param result the validated NLP translation result
     * @param records the records that should be filtered
     * @return a list containing only the matching records
     */
    public List<Map<String, String>> applyFilter(
            FlexibleNLPResult result,
            List<Map<String, String>> records
    ) {

        /*
         * Return all records when:
         * - The AI explicitly requested ALL records, or
         * - No filter conditions are available.
         */
        if ("ALL".equals(result.command) || result.conditions.isEmpty()) {
            return records;
        }

        // Store records that satisfy the filter conditions.
        List<Map<String, String>> matched = new ArrayList<>();

        /*
         * Evaluate each record independently.
         */
        for (Map<String, String> record : records) {

            /*
             * Determine whether conditions should use AND or OR logic.
             *
             * AND starts as true because:
             * true && condition = condition
             *
             * OR starts as false because:
             * false || condition = condition
             */
            boolean isAnd = "AND".equalsIgnoreCase(result.logic);
            boolean overall = isAnd;

            // Evaluate every condition against the current record.
            for (Condition c : result.conditions) {

                /*
                 * Retrieve the actual value from the record and evaluate it
                 * against the condition generated by the NLP model.
                 */
                boolean condResult = evaluateCondition(
                        record.get(c.field),
                        c.op,
                        c.value
                );

                /*
                 * Combine the current result with the overall result
                 * according to the selected logical operator.
                 */
                overall = isAnd
                        ? (overall && condResult)
                        : (overall || condResult);
            }

            // Add the record when all/any required conditions are satisfied.
            if (overall) {
                matched.add(record);
            }
        }

        // Return all matching records.
        return matched;
    }

    /**
     * Evaluates one filter condition against an actual record value.
     *
     * <p>The method first attempts numeric comparison when both values can
     * be converted to {@code double}. If numeric parsing fails, it performs
     * a case-insensitive string comparison.</p>
     *
     * @param actual the actual value stored in the record
     * @param op the comparison operator
     * @param expected the expected value from the filter condition
     * @return {@code true} if the condition matches; otherwise {@code false}
     */
    private boolean evaluateCondition(
            String actual,
            String op,
            String expected
    ) {

        // A missing field value cannot satisfy a condition.
        if (actual == null) {
            return false;
        }

        /*
         * Attempt numeric comparison first.
         *
         * This allows values such as:
         * age > 30
         * salary >= 60000
         */
        try {
            double a = Double.parseDouble(actual.trim());
            double e = Double.parseDouble(expected.trim());

            // Evaluate the numeric values using the requested operator.
            return switch (op) {
                case "=" -> a == e;
                case "!=" -> a != e;
                case ">" -> a > e;
                case "<" -> a < e;
                case ">=" -> a >= e;
                case "<=" -> a <= e;

                // "contains" is not meaningful for numeric values.
                default -> false;
            };

        } catch (NumberFormatException ignored) {

            /*
             * If either value is not numeric, continue with
             * case-insensitive string comparison.
             */
        }

        // Normalize both values before text comparison.
        String a = actual.trim().toLowerCase();
        String e = expected.trim().toLowerCase();

        // Evaluate supported text operations.
        return switch (op) {

            // Exact case-insensitive match.
            case "=" -> a.equals(e);

            // Case-insensitive inequality.
            case "!=" -> !a.equals(e);

            // Partial case-insensitive text match.
            case "contains" -> a.contains(e);

            /*
             * Numeric operators are not supported for non-numeric text.
             */
            default -> false;
        };
    }

    /**
     * Validates the structured result returned by the AI model.
     *
     * <p>This validation acts as a safety layer between the AI-generated
     * output and the actual dataset operations.</p>
     *
     * @param r the NLP result to validate
     * @param schema the actual list of dataset column names
     * @throws IllegalArgumentException if the generated result contains
     *                                  an invalid command, field, or operator
     */
    private void validate(
            FlexibleNLPResult r,
            List<String> schema
    ) {

        /*
         * Ensure that Gemini generated a command supported by this service.
         */
        if (!Set.of("FILTER", "ALL", "UNSUPPORTED").contains(r.command)) {
            throw new IllegalArgumentException(
                    "Unknown command from model: " + r.command
            );
        }

        /*
         * Additional validation is required for FILTER commands.
         */
        if ("FILTER".equals(r.command)) {

            // FILTER must contain at least one condition.
            if (r.conditions.isEmpty()) {
                throw new IllegalArgumentException(
                        "FILTER command requires at least one condition."
                );
            }

            // Validate every generated condition.
            for (Condition c : r.conditions) {

                /*
                 * Prevent the AI from referencing a column that does not
                 * actually exist in the uploaded dataset.
                 */
                if (!schema.contains(c.field)) {
                    throw new IllegalArgumentException(
                            "Unknown field in condition: " + c.field
                    );
                }

                /*
                 * Ensure that the operator is one of the explicitly
                 * supported operators.
                 */
                if (!ALLOWED_OPS.contains(c.op)) {
                    throw new IllegalArgumentException(
                            "Unsupported operator: " + c.op
                    );
                }
            }
        }
    }

    /**
     * Builds the system prompt sent to the Gemini API.
     *
     * <p>The prompt dynamically includes the actual dataset schema so the
     * AI model cannot safely assume fixed column names.</p>
     *
     * <p>It also defines:</p>
     * <ul>
     *     <li>Supported commands.</li>
     *     <li>Supported operators.</li>
     *     <li>The exact JSON response format.</li>
     *     <li>Examples of expected translations.</li>
     * </ul>
     *
     * @param schema the actual column names available in the dataset
     * @return the complete system instruction for Gemini
     */
    private String buildSystemPrompt(List<String> schema) {

        /*
         * Java text blocks make it easier to define a large multi-line
         * prompt while preserving formatting.
         *
         * The %s placeholder is replaced with the actual dataset columns.
         */
        return """
            You translate natural language into a JSON filter specification
            for a dataset with the following columns (this is the ONLY schema
            you may reference — do not invent fields that aren't listed):

            COLUMNS: %s

            ALLOWED COMMANDS:
              1. FILTER -> requires "conditions": a list of {field, op, value}
                 and "logic": "AND" or "OR" (default AND if only one condition)
              2. ALL -> return every record, no filtering
              3. UNSUPPORTED -> the request needs something these columns/ops
                 can't express (e.g. aggregation, sorting, joins, a field that
                 doesn't exist). Include a short "reason".

            ALLOWED OPERATORS: =, !=, >, <, >=, <=, contains
            (use "contains" for partial text matches, numeric ops for numbers)

            Respond with ONLY raw JSON, no markdown fences, no preamble. Exact shape:
            {"command": "FILTER|ALL|UNSUPPORTED", "logic": "AND|OR", "conditions": [{"field": "...", "op": "...", "value": "..."}], "reason": null}

            Examples (assume columns: name, age, city, department, salary):

            User: "show everyone"
            {"command": "ALL", "logic": "AND", "conditions": [], "reason": null}

            User: "employees older than 30 in Delhi"
            {"command": "FILTER", "logic": "AND", "conditions": [{"field": "age", "op": ">", "value": "30"}, {"field": "city", "op": "=", "value": "Delhi"}], "reason": null}

            User: "people in sales or marketing"
            {"command": "FILTER", "logic": "OR", "conditions": [{"field": "department", "op": "=", "value": "Sales"}, {"field": "department", "op": "=", "value": "Marketing"}], "reason": null}

            User: "salary above 60000"
            {"command": "FILTER", "logic": "AND", "conditions": [{"field": "salary", "op": ">", "value": "60000"}], "reason": null}

            User: "sort by salary descending"
            {"command": "UNSUPPORTED", "logic": "AND", "conditions": [], "reason": "Sorting isn't supported yet — only filtering by column values."}
            """.formatted(String.join(", ", schema));
    }

    /**
     * Removes Markdown code fences from an AI-generated response.
     *
     * <p>Although the Gemini prompt explicitly requests raw JSON, AI models
     * may occasionally return JSON inside Markdown code fences such as:</p>
     *
     * <pre>{@code
     * ```json
     * {"command":"ALL"}
     * ```
     * }</pre>
     *
     * <p>This method extracts only the content inside the code fence.
     * If no code fence exists, the original trimmed text is returned.</p>
     *
     * @param text the raw text returned by the AI model
     * @return cleaned JSON text without Markdown code fences
     */
    private String stripCodeFences(String text) {

        /*
         * Match:
         * ```json
         * JSON content
         * ```
         *
         * The "json" language identifier is optional.
         */
        Matcher m = Pattern
                .compile("```(?:json)?\\s*([\\s\\S]*?)```")
                .matcher(text);

        // Return extracted content when a code block exists.
        // Otherwise, simply return the trimmed original response.
        return m.find()
                ? m.group(1).trim()
                : text.trim();
    }
}

