package com.formulaquery.api;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;

/**
 * Represents a user in the FormulaQuery application.
 *
 * <p>This class is mapped to the "users" collection in MongoDB.
 * It stores user account information such as name, email,
 * password, OTP, and OTP expiry time.</p>
 *
 * <p>The email field is unique, ensuring that no two users
 * can register with the same email address.</p>
 *
 * @author Abdul Qadir
 * @version 1.0
 */
@Document(collection = "users")
public class User {

    /**
     * Unique identifier generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Full name of the user.
     */
    private String name;

    /**
     * User's email address.
     * This field is indexed and must be unique.
     */
    @Indexed(unique = true)
    private String email;

    /**
     * User's account password.
     */
    private String password;

    /**
     * One-Time Password (OTP) used for password reset.
     */
    private String otp;

    /**
     * Expiry time of the OTP.
     * Stored as a String representation of LocalDateTime.
     */
    private String otpExpiry;

    /**
     * Default constructor.
     * Required by Spring Data MongoDB.
     */
    public User() {}

    /**
     * Creates a new user with the given details.
     *
     * @param name User's full name.
     * @param email User's email address.
     * @param password User's password.
     */
    public User(String name, String email, String password) {
        this.name = name;
        this.email = email;
        this.password = password;
    }

    /**
     * Returns the unique MongoDB ID.
     *
     * @return User ID.
     */
    public String getId() {
        return id;
    }

    /**
     * Returns the user's name.
     *
     * @return User name.
     */
    public String getName() {
        return name;
    }

    /**
     * Updates the user's name.
     *
     * @param name New user name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the user's email.
     *
     * @return User email.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Updates the user's email.
     *
     * @param email New email address.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the user's password.
     *
     * @return User password.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Updates the user's password.
     *
     * @param password New password.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the stored OTP.
     *
     * @return OTP value.
     */
    public String getOtp() {
        return otp;
    }

    /**
     * Updates the OTP.
     *
     * @param otp New OTP.
     */
    public void setOtp(String otp) {
        this.otp = otp;
    }

    /**
     * Returns the OTP expiry time.
     *
     * @return OTP expiry as a String.
     */
    public String getOtpExpiry() {
        return otpExpiry;
    }

    /**
     * Updates the OTP expiry time.
     *
     * @param otpExpiry Expiry time as a String.
     */
    public void setOtpExpiry(String otpExpiry) {
        this.otpExpiry = otpExpiry;
    }
}